version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  mysql:
    image: mysql:8.3.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # 네가 원하는 패스워드 설정
      MYSQL_DATABASE: healthfriend       # 네가 사용할 DB 이름
      MYSQL_USER: hfuser                 # 네가 사용할 DB 유저명
      MYSQL_PASSWORD: hfpassword         # 네가 사용할 DB 유저 패스워드
    volumes:
      - mysql-data:/var/lib/mysql        # MySQL 데이터를 컨테이너 외부에 저장하기 위함
    restart: always

  app:
    image: your-spring-app:latest
    container_name: spring_app
    depends_on:
      - redis
      - mysql  # MySQL도 실행 후에 앱을 띄워야 함
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: no-auth
      SECRET_OAUTH2_KAKAO_CLIENT_ID_REST_API: ${SECRET_OAUTH2_KAKAO_CLIENT_ID_REST_API}
      SECRET_OAUTH2_KAKAO_CLIENT_ID_JS: ${SECRET_OAUTH2_KAKAO_CLIENT_ID_JS}
      SECRET_OAUTH2_GOOGLE_CLIENT_ID: ${SECRET_OAUTH2_GOOGLE_CLIENT_ID}
      SECRET_OAUTH2_GOOGLE_CLIENT_SECRET: ${SECRET_OAUTH2_GOOGLE_CLIENT_SECRET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SQS_ALARM_QUEUE_URL: ${AWS_SQS_ALARM_QUEUE_URL}
      AWS_SQS_DB_QUEUE_URL: ${AWS_SQS_DB_QUEUE_URL}
      AWS_REGION: ap-northeast-2
      REDIS_HOST: redis://redis:6379
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/healthfriend?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: hfuser
      SPRING_DATASOURCE_PASSWORD: hfpassword
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"
        reservations:
          cpus: "0.5"
          memory: "512M"

volumes:
  mysql-data: