spring:
  profiles:
    active:
      - secret
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/healthfriend?autoReconnect=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    # username과 password는 Local 개발 환경이므로 편의상 공개해 놓음
    # 배포 환경에서는 application-secret.yml 파일에 저장
    username: scott
    password: tiger

logging:
  level:
    org:
      springframework:
        security: trace
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
        type:
          descriptor:
            sql:
              BasicBinder: trace
    com:
      hf:
        healthfriend: trace

springdoc:
  packages-to-scan: com.hf.healthfriend
  override-with-generic-response: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha