spring:
  profiles:
    active:
      - secret
      - constants
      - priv # 각각 개발 환경에 따라 개별 설정이 필요할 수 있으므로

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 7MB


logging:
  level:
    org:
      springframework:
        security: trace
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
        type:
          descriptor:
            sql:
              BasicBinder: trace
    com:
      hf:
        healthfriend: trace

management:
  endpoint:
    beans:
      enabled: true
  endpoints:
    web:
      exposure:
        include: beans

springdoc:
  packages-to-scan: com.hf.healthfriend
  override-with-generic-response: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha

client:
  domain: localhost
  origin: http://localhost:3000

server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: local-dev

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hf
    # username과 password는 Local 개발 환경이므로 편의상 공개해 놓음
    # 배포 환경에서는 application-secret.yml 파일에 저장
    username: root
    password: 1111