user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid       /var/run/nginx.pid;
events {
    worker_connections 1024;
}

http {
    limit_req_zone $binary_remote_addr zone=my_limit:10m rate=10r/s;

    # 로드 밸런싱을 위한 업스트림 설정
    upstream spring_backend {
        server spring1:8080;
    }

    # 기본 서버 설정
    server {
        listen 80;
        server_name api.healthfriend.site;

        # 80 포트로 오는 요청을 443 포트로 리다이렉션
        location / {
            return 308 https://api.healthfriend.site$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name api.healthfriend.site;

        ssl_certificate /etc/ca-certificates/fullchain.pem;
        ssl_certificate_key /etc/ca-certificates/privkey.pem;

        # 모든 요청을 spring_backend 로드밸런싱으로 전달
        location / {
            limit_req zone=my_limit burst=10 nodelay;
            limit_req_status 429;

            proxy_pass http://spring1:8080;
            # 클라이언트가 요청한 호스트 이름
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Host $host;
            # 클라이언트 IP
            proxy_set_header X-Real-IP $remote_addr;
            # 프록시를 거치는 경우에도 원본 클라이언트 IP 유지를 위해 클라이언트 IP + 프록시 체인
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # 클라이언트 요청 프로토콜 (HTTP or HTTPS)
            proxy_set_header X-Forwarded-Proto $scheme;
            # 웹소켓
            proxy_http_version 1.1;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Upgrade $http_upgrade;

            # 연결 타임아웃 설정
            proxy_connect_timeout 5s;
            proxy_read_timeout 60s;
            proxy_send_timeout 60s;
        }
    }
}