server {
    listen 80;
    server_name api.healthfriend.site;

    location /.well-known/acme-challenge/ {
        alias /var/www/certbot/.well-known/acme-challenge/;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name api.healthfriend.site;

    ssl_certificate /etc/letsencrypt/live/api.healthfriend.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.healthfriend.site/privkey.pem;

    location / {
        proxy_pass http://spring-container:8080;
        proxy_http_version 1.1; # 웹소켓 위해 필요
        proxy_set_header Upgrade $http_upgrade; # Upgrade 헤더
        proxy_set_header Connection "Upgrade";  # Upgrade 헤더를 처리하도록 명시

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}