events {
    worker_connections 1024;
}

http {
    # 로드 밸런싱을 위한 업스트림 설정
    upstream spring_backend {
        server spring2:8080;
    }

    # 기본 서버 설정
    server {
        listen 80;
        server_name localhost;

        # 모든 요청을 spring_backend 로드밸런싱으로 전달
        location / {
            proxy_pass http://spring_backend;
            # 클라이언트가 요청한 호스트 이름
            proxy_set_header Host $host;
            # 클라이언트 IP
            proxy_set_header X-Real-IP $remote_addr;
            # 프록시를 거치는 경우에도 원본 클라이언트 IP 유지를 위해 클라이언트 IP + 프록시 체인
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # 클라이언트 요청 프로토콜 (HTTP or HTTPS)
            proxy_set_header X-Forwarded-Proto $scheme;

            # 연결 타임아웃 설정
            proxy_connect_timeout 5s;
            proxy_read_timeout 60s;
            proxy_send_timeout 60s;
        }
    }
}